"""add_escalation_fields_to_conversations

Revision ID: adc44d46353f
Revises: ec813e39898b
Create Date: 2026-06-08 23:34:40.385658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adc44d46353f'
down_revision: Union[str, None] = 'ec813e39898b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('escalation_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('last_escalation_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_escalation_at')
    op.drop_column('conversations', 'escalation_count')
    # ### end Alembic commands ###
