"""add_wamid_to_messages

Revision ID: ec813e39898b
Revises: 0030
Create Date: 2026-06-08 23:23:04.080118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec813e39898b'
down_revision: Union[str, None] = '0030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'message_template',
               existing_type=sa.TEXT(),
               comment='Supports {name} placeholder for personalisation.',
               existing_nullable=False)
    op.drop_index(op.f('ix_clients_api_key'), table_name='clients')
    op.drop_constraint(op.f('uq_clients_catalogue_slug'), 'clients', type_='unique')
    op.create_unique_constraint(None, 'clients', ['api_key'])
    op.drop_constraint(op.f('uq_customers_client_phone'), 'customers', type_='unique')
    op.drop_index(op.f('ix_follow_ups_sent_at'), table_name='follow_ups')
    op.add_column('messages', sa.Column('wamid', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_wamid'), 'messages', ['wamid'], unique=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'COD'::character varying"))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('restock_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restock_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'COD'::character varying"))
    op.drop_index(op.f('ix_messages_wamid'), table_name='messages')
    op.drop_column('messages', 'wamid')
    op.create_index(op.f('ix_follow_ups_sent_at'), 'follow_ups', ['sent_at'], unique=False)
    op.create_unique_constraint(op.f('uq_customers_client_phone'), 'customers', ['client_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_unique_constraint(op.f('uq_clients_catalogue_slug'), 'clients', ['catalogue_slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_clients_api_key'), 'clients', ['api_key'], unique=True)
    op.alter_column('campaigns', 'message_template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supports {name} placeholder for personalisation.',
               existing_nullable=False)
    # ### end Alembic commands ###
