"""
Render a stored `Invoice` as an A4 GST tax-invoice PDF (ReportLab, already a dependency).

Pure function of the invoice row: nothing is stored on disk, so the PDF can be regenerated byte-for-byte
equivalent at any time (download endpoint, e-mail attachment) and can never drift from the database.
"""

from __future__ import annotations

import io
import textwrap
from datetime import timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from app.models.sellertalk24_billing import Invoice
from app.services.billing.invoices import IST, state_name

GREEN = colors.HexColor("#0F8B4C")
NAVY = colors.HexColor("#1A2E44")
GREY = colors.HexColor("#6B7280")
LINE = colors.HexColor("#D1D5DB")


def rupees(paise: int) -> str:
    """Paise -> "Rs. 5,426.82" (Indian digit grouping; ReportLab's base fonts have no rupee glyph)."""
    sign = "-" if paise < 0 else ""
    whole, frac = divmod(abs(paise), 100)
    digits = str(whole)
    if len(digits) > 3:
        head, tail = digits[:-3], digits[-3:]
        groups = []
        while len(head) > 2:
            groups.insert(0, head[-2:])
            head = head[:-2]
        if head:
            groups.insert(0, head)
        digits = ",".join(groups + [tail])
    return f"{sign}Rs. {digits}.{frac:02d}"


def _wrap(value: str | None, width: int) -> list[str]:
    """Wrap free text (addresses) to *width* characters, keeping explicit line breaks."""
    lines: list[str] = []
    for raw in (value or "").splitlines() or [""]:
        lines.extend(textwrap.wrap(raw, width) or [""])
    return lines


def render_invoice_pdf(inv: Invoice) -> bytes:
    """Return the PDF bytes for *inv*."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(f"Invoice {inv.invoice_number}")
    c.setAuthor(inv.seller_name)
    width, height = A4
    left, right = 40, width - 40

    # ── header ──
    c.setFillColor(GREEN)
    c.rect(0, height - 70, width, 70, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(left, height - 42, "TAX INVOICE")
    c.setFont("Helvetica", 10)
    c.drawRightString(right, height - 36, inv.seller_name)
    c.drawRightString(right, height - 50, "SellerTalk24 — AI sales agent for WhatsApp & Instagram")

    # ── invoice meta ──
    y = height - 100
    issued = inv.issued_at.astimezone(IST) if inv.issued_at.tzinfo else inv.issued_at.replace(tzinfo=timezone.utc).astimezone(IST)
    c.setFillColor(NAVY)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left, y, f"Invoice No: {inv.invoice_number}")
    c.drawRightString(right, y, f"Date: {issued:%d %b %Y}")
    c.setFont("Helvetica", 9)
    c.setFillColor(GREY)
    c.drawString(left, y - 14, f"Financial year: {inv.financial_year}")
    c.drawRightString(right, y - 14, f"Currency: {inv.currency}")

    # ── seller / buyer ──
    y -= 44
    col2 = left + 270

    def block(x: float, title: str, rows: list[str]) -> float:
        yy = y
        c.setFillColor(GREEN)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(x, yy, title)
        yy -= 14
        c.setFillColor(NAVY)
        for i, row in enumerate(rows):
            c.setFont("Helvetica-Bold" if i == 0 else "Helvetica", 10 if i == 0 else 9)
            c.drawString(x, yy, row)
            yy -= 12
        return yy

    seller_state = f"{state_name(inv.seller_state_code)} ({inv.seller_state_code})".strip()
    seller_rows = [inv.seller_name, f"GSTIN: {inv.seller_gstin or '—'}", *_wrap(inv.seller_address, 42), f"State: {seller_state}"]
    buyer_rows = [inv.buyer_name or "—", f"GSTIN: {inv.buyer_gstin or 'Unregistered / not provided'}"]
    buyer_rows += _wrap(inv.buyer_address, 42)
    buyer_rows.append(inv.buyer_email)
    end_seller = block(left, "SOLD BY", seller_rows)
    end_buyer = block(col2, "BILLED TO", buyer_rows)
    y = min(end_seller, end_buyer) - 4

    # Place of supply: the buyer's GSTIN state; with none, the seller's own state (intra-state supply).
    pos_code = inv.buyer_state_code or inv.seller_state_code
    c.setFillColor(NAVY)
    c.setFont("Helvetica", 9)
    c.drawString(left, y, f"Place of supply: {state_name(pos_code)} ({pos_code})")
    c.drawRightString(
        right, y, "Supply type: " + ("Intra-state (CGST + SGST)" if inv.intra_state else "Inter-state (IGST)")
    )

    # ── line item table ──
    y -= 26
    cols = {"desc": left + 6, "sac": left + 268, "taxable": right - 148, "tax": right - 76, "total": right - 6}
    c.setFillColor(NAVY)
    c.rect(left, y - 6, right - left, 20, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 8.5)
    c.drawString(cols["desc"], y, "Description")
    c.drawString(cols["sac"], y, "SAC")
    c.drawRightString(cols["taxable"], y, "Taxable value")
    c.drawRightString(cols["tax"], y, f"GST @{inv.gst_rate_bps / 100:g}%")
    c.drawRightString(cols["total"], y, "Amount")

    y -= 20
    c.setFillColor(NAVY)
    c.setFont("Helvetica", 9)
    desc_lines = _wrap(inv.description, 52)
    for i, line in enumerate(desc_lines):
        c.drawString(cols["desc"], y - 11 * i, line)
    c.drawString(cols["sac"], y, inv.sac_code)
    gst_total = inv.cgst_paise + inv.sgst_paise + inv.igst_paise
    c.drawRightString(cols["taxable"], y, rupees(inv.taxable_paise))
    c.drawRightString(cols["tax"], y, rupees(gst_total))
    c.drawRightString(cols["total"], y, rupees(inv.total_paise))
    y -= 11 * len(desc_lines) + 8
    c.setStrokeColor(LINE)
    c.line(left, y, right, y)

    # ── totals ──
    y -= 22
    label_x, value_x = right - 170, right - 6

    def total_row(label: str, value: str, bold: bool = False) -> None:
        nonlocal y
        c.setFont("Helvetica-Bold" if bold else "Helvetica", 10 if bold else 9)
        c.setFillColor(NAVY if bold else GREY)
        c.drawString(label_x, y, label)
        c.drawRightString(value_x, y, value)
        y -= 15

    half = f"{inv.gst_rate_bps / 200:g}%"
    total_row("Plan price", rupees(inv.base_paise))
    if inv.credit_paise:
        total_row("Less: upgrade credit", "-" + rupees(inv.credit_paise))
    total_row("Taxable value", rupees(inv.taxable_paise))
    if inv.intra_state:
        total_row(f"CGST @{half}", rupees(inv.cgst_paise))
        total_row(f"SGST @{half}", rupees(inv.sgst_paise))
    else:
        total_row(f"IGST @{inv.gst_rate_bps / 100:g}%", rupees(inv.igst_paise))
    c.setStrokeColor(NAVY)
    c.line(label_x, y + 9, value_x, y + 9)
    y -= 4
    total_row("TOTAL", rupees(inv.total_paise), bold=True)

    # ── payment + footer ──
    y -= 18
    c.setFillColor(NAVY)
    c.setFont("Helvetica", 9)
    if inv.razorpay_payment_id:
        c.drawString(left, y, f"Paid online via Razorpay — payment id {inv.razorpay_payment_id}")
        y -= 12
    c.setFillColor(GREY)
    c.setFont("Helvetica", 8)
    c.drawString(left, y, "Digital service — no physical goods are shipped. Amounts are in Indian Rupees.")
    c.drawString(left, 40, "This is a computer-generated invoice and does not require a signature.")
    c.drawRightString(right, 40, inv.invoice_number)
    c.showPage()
    c.save()
    return buf.getvalue()
